title: Temple and Shrine sites from Britian & Ireland 100 BCE to 100 CE
description: Sites and associated data, such as chronology, address, lat, long, tags, and bibliography, with finds that have a Temple or Shrine from the years 100 BCE to 100 CE in Britian & Ireland 

publisher_text: Templum Project
publisher_url: https://8bitsensei.github.io/Templum/

license_text: 
license_url: 

frequency: 

certificate_embed: 
